--
-- Table structure for table "admin"
--
DROP TABLE IF EXISTS "tb_admin";

CREATE TABLE "tb_admin" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "password" varchar(255),
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("email")
);

CREATE UNIQUE INDEX "id_Admin_UNIQUE" ON "tb_admin" ("id" ASC);
