-- Table structure for table "config"
DROP TABLE IF EXISTS "tb_config";
CREATE TABLE "tb_config" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "value" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id")
);



-- Table structure for table "tb_user_type"
DROP TABLE IF EXISTS "tb_user_type";
CREATE TABLE "tb_user_type" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "type" varchar(255) NOT NULL,
  "description" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "id_tb_user_type_UNIQUE" ON "tb_user_type" ("id" ASC);



-- Table structure for table "user"
DROP TABLE IF EXISTS "tb_user";
CREATE TABLE "tb_user" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "user_wallet_id" INT8 NOT NULL,
  "user_type_id" INT8 NOT NULL,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "is_admin" BOOLEAN DEFAULT FALSE, 
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("email"),
  CONSTRAINT "tk_tb_user_tb_user_wallet" FOREIGN KEY ("user_wallet_id") REFERENCES "tb_user_wallet" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_tb_user_tb_user_type" FOREIGN KEY ("user_type_id") REFERENCES "tb_user_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_user_UNIQUE" ON "tb_user" ("id" ASC);
CREATE INDEX "fk_tb_user_tb_user_wallet_idx" ON "tb_user" ("user_wallet_id" ASC);
CREATE INDEX "fk_tb_user_tb_user_type_idx" ON "tb_user" ("user_type_id" ASC);



-- Table structure for table "user group"
DROP TABLE IF EXISTS "tb_user_group";
CREATE TABLE "tb_user_group" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "description" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "id_tb_user_group_UNIQUE" ON tb_user_group ("id" ASC);



-- Table structure for table "user route"
DROP TABLE IF EXISTS "tb_user_route";
CREATE TABLE "tb_user_route" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "route" varchar(255) NOT NULL,
  "method" varchar(255) NOT NULL,
  "description" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "id_tb_user_route_UNIQUE" ON "tb_user_route" ("id" ASC);



-- Table structure for table "user wallet"
DROP TABLE IF EXISTS "tb_user_wallet";
CREATE TABLE "tb_user_wallet" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "userId" INT8 NOT NULL,
  "address" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_user_wallet_tb_user" FOREIGN KEY ("user_id") REFERENCES "tb_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_user_wallet_UNIQUE" ON "tb_user_wallet" ("id" ASC);
CREATE INDEX "fk_tb_user_wallet_tb_user_idx" ON "tb_user_wallet" ("user_id" ASC);



-- Table structure for table "tb_bs"
DROP TABLE IF EXISTS "tb_bs";
CREATE TABLE "tb_bs" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "bs_wallet_id" INT8 NOT NULL,
  "bs_profit_balance_id" INT8 NOT NULL,
  "bs_profit_balance_sm_id" INT8 NOT NULL,
  "name" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_bs_tb_bs_wallet" FOREIGN KEY ("bs_wallet_id") REFERENCES "tb_bs_wallet" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_bs_tb_bs_profit_balance" FOREIGN KEY ("bs_profit_balance_id") REFERENCES "tb_bs_profit_balance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_bs_tb_bs_profit_balance_sm" FOREIGN KEY ("bs_profit_balance_sm_id") REFERENCES "tb_bs_profit_balance_sm" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_bs_UNIQUE" ON "tb_bs" ("id" ASC);
CREATE INDEX "fk_tb_bs_tb_bs_wallet_idx" ON "tb_bs" ("bs_wallet_id" ASC);
CREATE INDEX "fk_tb_bs_tb_bs_profit_balance_idx" ON "tb_bs" ("bs_profit_balance_id" ASC);
CREATE INDEX "fk_tb_bs_tb_bs_profit_balance_sm_idx" ON "tb_bs" ("bs_profit_balance_sm_id" ASC);



-- Table structure for table "tb_bs_wallet"
DROP TABLE IF EXISTS "tb_bs_wallet";
CREATE TABLE "tb_bs" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "bs_id" INT8 NOT NULL,
  "address" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_bs_wallet_tb_bs" FOREIGN KEY ("bs_id") REFERENCES "tb_bs" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_bs_wallet_UNIQUE" ON "tb_bs_wallet" ("id" ASC);
CREATE INDEX "fk_tb_bs_wallet_tb_bs_idx" ON "tb_bs_wallet" ("bs_id" ASC);



-- Table structure for table "business profit balance simulation"
DROP TABLE IF EXISTS "tb_bs_profit_balance_sm";
CREATE TABLE "tb_bs_profit_balance_sm" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "bs_id" INT8 NOT NULL,
  "netValue" DECIMAL NOT NULL,
  "reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_bs_profit_balance_sm_tb_bs" FOREIGN KEY ("bs_id") REFERENCES "tb_bs" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_bs_profit_balance_sm_UNIQUE" ON "tb_bs_profit_balance_sm" ("id" ASC);
CREATE INDEX "fk_tb_bs_profit_balance_sm_tb_bs_idx" ON "tb_bs_profit_balance_sm" ("bs_id" ASC);



-- Table structure for table "business profit balance"
DROP TABLE IF EXISTS "tb_bs_profit_balance";
CREATE TABLE "tb_bs_profit_balance" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "bs_id" INT8 NOT NULL,
  "netValue" DECIMAL NOT NULL,
  "reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_bs_profit_balance_tb_bs" FOREIGN KEY ("bs_id") REFERENCES "tb_bs" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_bs_profit_balance_UNIQUE" ON "tb_bs_profit_balance" ("id" ASC);
CREATE INDEX "fk_tb_bs_profit_balance_tb_bs_idx" ON "tb_bs_profit_balance" ("bs_id" ASC);



-- Table structure for table "business future balance"
DROP TABLE IF EXISTS "tb_bs_future_balance";
CREATE TABLE "tb_bs_future_balance" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "balance_origin_type_id" INT8 NOT NULL,
  "units" DECIMAL NOT NULL,
  "reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_bs_future_balance_tb_balance_origin_type" FOREIGN KEY ("balance_origin_type_id") REFERENCES "tb_balance_origin_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_bs_future_balance_UNIQUE" ON "tb_bs_future_balance" ("id" ASC);
CREATE INDEX "fk_tb_bs_future_balance_tb_balance_origin_type_idx" ON "tb_bs_future_balance" ("balance_origin_type_id" ASC);



-- Table structure for table "business future balance simulation"
DROP TABLE IF EXISTS "tb_bs_future_balance_sm";
CREATE TABLE "tb_bs_future_balance_sm" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "balance_origin_type_id" INT8 NOT NULL,
  "user_id" INT8 NOT NULL,
  "units" DECIMAL NOT NULL,
  "reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_bs_future_balance_tb_balance_origin_type" FOREIGN KEY ("balance_origin_type_id") REFERENCES "tb_balance_origin_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
  CONSTRAINT "fk_tb_bs_future_balance_tb_user" FOREIGN KEY ("user_id") REFERENCES "tb_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_bs_future_balance_UNIQUE" ON "tb_bs_future_balance" ("id" ASC);
CREATE INDEX "fk_tb_bs_future_balance_tb_balance_origin_type_idx" ON "tb_bs_future_balance" ("balance_origin_type_id" ASC);
CREATE INDEX "fk_tb_bs_future_balance_tb_user_idx" ON "tb_user" ("user_id" ASC);



-- Table structure for table "future balance"
DROP TABLE IF EXISTS "tb_future_balance";
CREATE TABLE "tb_future_balance" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "investment_id" INT8 NOT NULL,
  "bs_future_balance_id" INT8 NOT NULL,
  "balance_origin_type_id" INT8 NOT NULL,
  "net_value" DECIMAL NOT NULL,
  "units" DECIMAL NOT NULL,
  "profit" DECIMAL NOT NULL,
  "reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_future_balance_tb_investment" FOREIGN KEY ("investment_id") REFERENCES "tb_investment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_future_balance_tb_bs_future_balance" FOREIGN KEY ("bs_future_balance_id") REFERENCES "tb_bs_future_balance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_future_balance_tb_balance_origin_type" FOREIGN KEY ("balance_origin_type_id") REFERENCES "tb_balance_origin_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_future_balance_UNIQUE" ON "tb_future_balance" ("id" ASC);
CREATE INDEX "fk_tb_future_balance_tb_investment_idx" ON "tb_future_balance" ("investment_id" ASC);
CREATE INDEX "fk_tb_future_balance_tb_bs_future_balance_idx" ON "tb_future_balance" ("bs_future_balance_id" ASC);
CREATE INDEX "fk_tb_future_balance_tb_balance_origin_type_idx" ON "tb_future_balance" ("balance_origin_type_id" ASC);



-- Table structure for table "business spot balance"
DROP TABLE IF EXISTS "tb_bs_spot_balance";
CREATE TABLE "tb_bs_spot_balance" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "cryptocurrency_id" INT8 NOT NULL,
  "balance_origin_type_id" INT8 NOT NULL,
  "net_value" DECIMAL NOT NULL,
  "units" DECIMAL NOT NULL,
  "profit" DECIMAL NOT NULL,
  "reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_bs_spot_balance_tb_cryptocurrency" FOREIGN KEY ("cryptocurrency_id") REFERENCES "tb_cryptocurrency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_bs_spot_balance_tb_balance_origin_type" FOREIGN KEY ("balance_origin_type_id") REFERENCES "tb_balance_origin_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_bs_spot_balance_UNIQUE" ON "tb_bs_spot_balance" ("id" ASC);
CREATE INDEX "fk_tb_bs_spot_balance_tb_cryptocurrency_idx" ON "tb_bs_spot_balance" ("cryptocurrency_id" ASC);
CREATE INDEX "fk_tb_bs_spot_balance_tb_balance_origin_type_idx" ON "tb_bs_spot_balance" ("balance_origin_type_id" ASC);



-- Table structure for table "spot balance"
DROP TABLE IF EXISTS "tb_spot_balance";
CREATE TABLE "tb_spot_balance" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "investment_id" INT8 NOT NULL,
  "bs_spot_balance_id" INT8 NOT NULL,
  "balance_origin_type_id" INT8 NOT NULL,
  "net_value" DECIMAL NOT NULL,
  "units" DECIMAL NOT NULL,
  "profit" DECIMAL NOT NULL,
  "reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_spot_balance_tb_investment" FOREIGN KEY ("investment_id") REFERENCES "tb_investment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_spot_balance_tb_bs_spot_balance" FOREIGN KEY ("bs_spot_balance_id") REFERENCES "tb_bs_spot_balance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_spot_balance_tb_balance_origin_type" FOREIGN KEY ("balance_origin_type_id") REFERENCES "tb_balance_origin_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_spot_balance_UNIQUE" ON "tb_spot_balance" ("id" ASC);
CREATE INDEX "fk_tb_spot_balance_tb_investment_idx" ON "tb_spot_balance" ("investment_id" ASC);
CREATE INDEX "fk_tb_spot_balance_tb_bs_spot_balance_idx" ON "tb_spot_balance" ("bs_spot_balance_id" ASC);
CREATE INDEX "fk_tb_spot_balance_tb_balance_origin_type_idx" ON "tb_spot_balance" ("balance_origin_type_id" ASC);



-- Table structure for table "business wallet"
DROP TABLE IF EXISTS "tb_bs_wallet";
CREATE TABLE "tb_bs_wallet" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "business_id" INT8 NOT NULL,
  "address" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_bs_wallet_tb_business" FOREIGN KEY ("business_id") REFERENCES "tb_business" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_bs_wallet_UNIQUE" ON "tb_bs_wallet" ("id" ASC);
CREATE INDEX "fk_tb_bs_wallet_tb_business_idx" ON "tb_bs_wallet" ("business_id" ASC);



-- Table structure for table "aport"
DROP TABLE IF EXISTS "tb_aport";
CREATE TABLE "tb_aport" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "cryptocurrency_id" INT8 NOT NULL,
  "value" DECIMAL NOT NULL,
  "reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_aport_tb_cryptocurrency" FOREIGN KEY ("cryptocurrency_id") REFERENCES "tb_cryptocurrency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_aport_UNIQUE" ON "tb_aport" ("id" ASC);
CREATE INDEX "fk_tb_aport_tb_cryptocurrency_idx" ON "tb_aport" ("cryptocurrency_id" ASC);



-- Table structure for table "cryptocurrency"
DROP TABLE IF EXISTS "tb_cryptocurrency";
CREATE TABLE "tb_cryptocurrency" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "symbol" varchar(255) NOT NULL,
  "name" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "id_tb_cryptocurrency_UNIQUE" ON "tb_cryptocurrency" ("id" ASC);



-- Table structure for table "income type"
DROP TABLE IF EXISTS "tb_income_type";
CREATE TABLE "tb_income_type" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "type" varchar(255) NOT NULL,
  "description" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "id_tb_income_type_UNIQUE" ON "tb_income_type" ("id" ASC);



-- Table structure for table "tb_document_type"
DROP TABLE IF EXISTS "tb_document_type";
CREATE TABLE "tb_document_type" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "type" varchar(255) NOT NULL,
  "description" varchar(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "id_tb_document_type_UNIQUE" ON "tb_document_type" ("id" ASC);



-- Table structure for table "document"
DROP TABLE IF EXISTS "tb_document";
CREATE TABLE "tb_document" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INT8 NOT NULL,
  "document_type_id" INT8 NOT NULL,
  "number" varchar(255) NOT NULL,
  "issuing_entity" varchar(255) NOT NULL,
  "issue_date" date NOT NULL, 
  "due_date" date NOT NULL,
  "main" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_document_tb_user" FOREIGN KEY ("user_id") REFERENCES "tb_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_document_tb_document_type" FOREIGN KEY ("document_type_id") REFERENCES "tb_document_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_document_UNIQUE" ON "tb_document" ("id" ASC);
CREATE INDEX "fk_tb_document_tb_user_idx" ON "tb_document" ("user_id" ASC);
CREATE INDEX "fk_tb_document_tb_document_type" ON "tb_document" ("document_type_id" ASC); 



-- Table structure for table "investment"
DROP TABLE IF EXISTS "tb_investment";
CREATE TABLE "tb_investment" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "user_id" INT8 NOT NULL,
  "cryptocurrency_id" INT8 NOT NULL,
  "spot_balance_id" INT8 NOT NULL,
  "future_balance_id" INT8 NOT NULL,
  "initial_value" DECIMAL NOT NULL,
  "unit_value" DECIMAL NOT NULL,
  "units" DECIMAL NOT NULL,
  "active" BOOLEAN NOT NULL,
  "simulated" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_investment_tb_user" FOREIGN KEY ("user_id") REFERENCES "tb_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_investment_tb_cryptocurrency" FOREIGN KEY ("cryptocurrency_id") REFERENCES "tb_cryptocurrency" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_investment_tb_spot_balance" FOREIGN KEY ("spot_balance_id") REFERENCES "tb_spot_balance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_investment_tb_future_balance" FOREIGN KEY ("future_balance_id") REFERENCES "tb_future_balance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
  );
CREATE UNIQUE INDEX "id_tb_investment_UNIQUE" ON "tb_investment" ("id" ASC);
CREATE INDEX "fk_tb_investment_tb_user_idx" ON "tb_investment" ("user_id" ASC);
CREATE INDEX "fk_tb_investment_tb_cryptocurrency_idx" ON "tb_investment" ("cryptocurrency_id" ASC);
CREATE INDEX "fk_tb_investment_tb_spot_balance_idx" ON "tb_investment" ("spot_balance_id" ASC);
CREATE INDEX "fk_tb_investment_tb_future_balance_idx" ON "tb_investment" ("future_balance_id" ASC);



-- Table structure for table "pivot investment income type"
DROP TABLE IF EXISTS "tb_pivot_investment_income_type";
CREATE TABLE "tb_pivot_investment_income_type" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "investment_id" INT8 NOT NULL,
  "income_type_id" INT8 NOT NULL,
  "reference_date" DATE NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_pivot_investment_income_type_tb_investment" FOREIGN KEY ("investment_id") REFERENCES "tb_investment" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_pivot_investment_income_type_tb_income_type" FOREIGN KEY ("income_type_id") REFERENCES "tb_income_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_pivot_investment_income_type_UNIQUE" ON "tb_pivot_investment_income_type" ("id" ASC);
CREATE INDEX "fk_tb_pivot_investment_income_type_tb_investment_idx" ON "tb_pivot_investment_income_type" ("investment_id" ASC);
CREATE INDEX "fk_tb_pivot_investment_income_type_tb_income_type_idx" ON "tb_pivot_investment_income_type" ("income_type_id" ASC);



-- Table structure for table "pivot user group and user"
DROP TABLE IF EXISTS "tb_pivot_user_group_user";
CREATE TABLE "tb_pivot_user_group_user" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "user_group_id" INT8 NOT NULL,
  "user_id" INT8 NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_pivot_user_group_user_tb_user" FOREIGN KEY ("user_id") REFERENCES "tb_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_pivot_user_group_user_tb_user_group" FOREIGN KEY ("user_group_id") REFERENCES "tb_user_group" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_pivot_user_group_user_UNIQUE" ON "tb_pivot_user_group_user" ("id" ASC);
CREATE INDEX "fk_tb_pivot_user_group_user_tb_user_group_idx" ON "tb_pivot_user_group_user" ("user_group_id" ASC);
CREATE INDEX "fk_tb_pivot_user_group_user_tb_user_idx" ON "tb_pivot_user_group_user" ("user_id" ASC);



-- Table structure for table "tb_pivot_user_group_user_route"
DROP TABLE IF EXISTS "tb_pivot_user_group_user_route";
CREATE TABLE "tb_pivot_user_group_user_route" (
  "id" INT8 GENERATED BY DEFAULT AS IDENTITY,
  "user_group_id" INT8 NOT NULL,
  "user_route_id" INT8 NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_tb_pivot_user_group_user_route_tb_user_group" FOREIGN KEY ("user_group_id") REFERENCES "tb_user_group" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT "fk_tb_pivot_user_group_user_route_tb_user_route" FOREIGN KEY ("user_route_id") REFERENCES "tb_user_route" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX "id_tb_pivot_user_group_user_route_UNIQUE" ON "tb_pivot_user_group_user_route" ("id" ASC);
CREATE INDEX "fk_tb_pivot_user_group_user_route_tb_user_group_idx" ON "tb_pivot_user_group_user_route" ("user_group_id" ASC);
CREATE INDEX "fk_tb_pivot_user_group_user_route_tb_user_route_idx" ON "tb_pivot_user_group_user_route" ("user_route_id" ASC);